config/routes.rb
Rails.application.routes.draw do
  resources :fullapplications
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  
  root 'welcome#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'welcome/about'
end
  

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :people
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: %i[ show edit update destroy ]

  

  # GET /phones or /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to phone_url(@phone), notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to phone_url(@phone), notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @phone.destroy

    respond_to do |format|
      format.html { redirect_to phones_url, notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      params.require(:phone).permit(:phone_number, :comment, :people_id)
    end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<%= form_with(model: phone) do |form| %>
  <% if phone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
        <% phone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.label :people_id, style: "display: block" %>
    <%= form.text_field :people_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/phones/_phone.html.erb
<div id="<%= dom_id phone %>">
  <p>
    <strong>Phone number:</strong>
    <%= phone.phone_number %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= phone.comment %>
  </p>

  <p>
    <strong>People:</strong>
    <%= phone.people_id %>
  </p>

</div>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to "Show this phone", @phone %> |
  <%= link_to "Back to phones", phones_path %>
</div>

app/views/phones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Phones</h1>

<div id="phones">
  <% @phones.each do |phone| %>
    <%= render phone %>
    <p>
      <%= link_to "Show this phone", phone %>
    </p>
  <% end %>
</div>

<%= link_to "New phone", new_phone_path %>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to "Back to phones", phones_path %>
</div>

app/views/phones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @phone %>

<div>
  <%= link_to "Edit this phone", edit_phone_path(@phone) %> |
  <%= link_to "Back to phones", phones_path %>

  <%= button_to "Destroy this phone", @phone, method: :delete %>
</div>