config/routes.rb
Rails.application.routes.draw do
  resources :fullapplications
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  
  root 'welcome#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'welcome/about'
end
  

app/models/person.rb
class Person < ApplicationRecord
    
    has_many :addresses, dependent: :destroy
    has_many :emails, dependent: :destroy
    has_many :phones, dependent: :destroy

    accepts_nested_attributes_for :addresses

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:suffix, :first_name, :last_name, :birtday, :comment, address_attributes: [:street, :city])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <div>
        <%= form.label :suffix, style: "display: block" %>
        <%= form.text_field :suffix %>
      </div>

      <div>
        <%= form.label :first_name, style: "display: block" %>
        <%= form.text_field :first_name %>
      </div>

      <div>
        <%= form.label :last_name, style: "display: block" %>
        <%= form.text_field :last_name %>
      </div>

      <div>
        <%= form.label :birtday, style: "display: block" %>
        <%= form.date_field :birtday %>
      </div>

      <div>
        <%= form.label :comment, style: "display: block" %>
        <%= form.text_area :comment %>
    </div>
    

    <div>
            <%= form.fields_for :address do |address_form|%>

              <%= address_form.label :street, style: 'display: block' %>
              <%= address_form.text_field :street %>

              <%= address_form.label :city, style: 'display: block' %>
              <%= address_form.text_field :city %>

              <% end %>
    </div>

    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Suffix:</strong>
    <%= person.suffix %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= person.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= person.last_name %>
  </p>

  <p>
    <strong>Birtday:</strong>
    <%= person.birtday %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= person.comment %>
  </p>
</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<div class ="card" style="width: 18rem;">
  <div class="card-body">
  
    <p style="color: green"><%= notice %></p>

    <h1>People</h1>

    <div id="people">
      <% @people.each do |person| %>
        <%= render person %>
        <p>
          <%= link_to "Show this person", person %>
        </p>
        <%= link_to "New person", new_person_path %>
      <% end %>
    </div>

     
   </div> 
    
  </div>

 

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>