config/routes.rb
Rails.application.routes.draw do
  resources :fullapplications
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  
  root 'welcome#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'welcome/about'
end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about 
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Address Book</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
            <%= link_to "Add an Address", new_fullapplication_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
        <%= link_to "List of Addresses", fullapplications_path, class:'nav-link' %>
        </li>
       
        <li class="nav-item">
            <%= link_to "About Us", welcome_about_path, class:'nav-link' %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/welcome/about.html.erb
<h1> About Page </h1>

<br>

<p> This is my technical assessment for Wikilane! I hope you enjoy, feel free to save as many addresses as you'd like! </p>

app/views/welcome/index.html.erb
<% if Current.user %>
    Logged in as: <%= Current.user.email %><br>
   
    <%= button_to 'Logout', logout_path, method: :delete %>
    <% else %>
    <%= link_to 'Sign Up', sign_up_path %>
    or
    <%= link_to 'Login', sign_in_path %>
  <% end %>
 
  <br>

  <br>

<h1>Welcome to my AddressBook! </h1>
<p>Click on "Add a new Address" to get started</p>