config/routes.rb
Rails.application.routes.draw do
  resources :fullapplications
  resources :phones
  resources :emails
  resources :addresses
  resources :people
  
  root 'welcome#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'welcome/about'
end
  

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:street, :town, :ZIP_code, :state, :country, :people_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Street:</strong>
    <%= address.street %>
  </p>

  <p>
    <strong>Town:</strong>
    <%= address.town %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= address.ZIP_code %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= address.country %>
  </p>

  <p>
    <strong>People:</strong>
    <%= address.people_id %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :town, style: "display: block" %>
    <%= form.text_field :town %>
  </div>

  <div>
    <%= form.label :ZIP_code, style: "display: block" %>
    <%= form.text_field :ZIP_code %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :people_id, style: "display: block" %>
    <%= form.text_field :people_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address %> |
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address) %> |
  <%= link_to "Back to addresses", addresses_path %>

  <%= button_to "Destroy this address", @address, method: :delete %>
</div>